name: Create a comment on new issues
jobs:
  run-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: "bot respond to issue"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -d '{"body":"A BOTS COMMENT"}'         
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OWNER: ${{github.event.repository.owner.login}}
          ISSUE_NUMBER: ${{github.event.issue.number}}
          REPOSITORY: ${{github.event.repository.name}}
on:
  issues:
    types: [opened]
