name: Create a comment on new issues
jobs:
  run-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{toJson(github.event)}}' | jq
        shell: bash
on:
  issues:
    types: [opened]
